# Generated by Django 3.1.7 on 2021-04-03 14:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='venue',
            managers=[
                ('venues', django.db.models.manager.Manager()),
            ],
        ),
    ]
