# Generated by Django 3.1.7 on 2021-03-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210316_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclubuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='User Email'),
        ),
    ]
